<?php

include_once('motionsplan_exercise.features.inc');

/**
* Implements hook_filter_info().
*/
function motionsplan_exercise_filter_info() {
  $filters = array();
  $filters['motionsplan_exercise'] = array(
    'title' => t('Motionsplan Exercise Reference'),
    'description' => t('Allows the user to include exercises in entities.'),
    'process callback' => '_motionsplan_exercise_filter_process',
    'tips callback' => '_motionsplan_exercise_tips',
    'cache' => TRUE,
  );
  return $filters;
}

/**
 * Implements filter process callback.
 */
function _motionsplan_exercise_filter_process($text, $filter, $format) {
  return preg_replace_callback('@\[motionsplan-exercise:?(.*)\]@', '_motionsplan_exercise_display_embed', $text);
}

/**
 * Implements filter tips callback.
 */
function _motionsplan_exercise_tips($filter, $format, $long = FALSE) {
  return t('Use [motionsplan-exercise:xxx] with xxx node id exercise');
}

/**
 * Utility function to do the hard work getting the images
 */
function _motionsplan_exercise_display_embed($matches) {
  $output = 'Her skal øvelse nummer ' . $matches[1] . ' vises. Vi arbejder på sagen.';
  return $output;
}
