<?php

include_once('motionsplan_exercise.features.inc');

/**
* Implements hook_filter_info().
*/
function motionsplan_exercise_filter_info() {
  $filters = array();
  $filters['motionsplan_exercise'] = array(
    'title' => t('Motionsplan Exercise Reference'),
    'description' => t('Allows the user to include exercises in entities.'),
    'process callback' => '_motionsplan_exercise_filter_process',
    'tips callback' => '_motionsplan_exercise_tips',
    'cache' => TRUE,
  );
  return $filters;
}

/**
 * Implements hook_entity_info_alter().
 */
function motionsplan_exercise_entity_info_alter(&$entity_info) {
  $entity_info['node']['view modes']['exercise_list'] = array(
    'label' => t('Exercise list'),
    'custom settings' => TRUE,
  );
}

/**
 * Implements hook_preprocess_node().
 */
function motionsplan_exercise_preprocess_node(&$vars) {
  if ($vars['view_mode'] == 'exercise_list') {
    $vars['theme_hook_suggestions'][] = 'node__' . $vars['type'] . '__exercise_list';
  }
}

/**
 * Implements filter process callback.
 */
function _motionsplan_exercise_filter_process($text, $filter, $format) {
  return preg_replace_callback('/\[motionsplan-exercise:?([^]]*)?\]/', '_motionsplan_exercise_display_embed', $text);
}

/**
 * Implements filter tips callback.
 */
function _motionsplan_exercise_tips($filter, $format, $long = FALSE) {
  return t('Use [motionsplan-exercise:xxx] with xxx node id exercise');
}

/**
 * Utility function to do the hard work getting the images
 */
function _motionsplan_exercise_display_embed($matches) {
  $output = '<strong>Her skal øvelse nummer ' . $matches[1] . ' vises. Vi arbejder på sagen.</strong>';
  return $output;
}

